# Generated by Django 2.0.8 on 2018-08-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='path_slug',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Optional. Set a path slug if you would like site functionality on a path site', max_length=255, verbose_name='path slug'),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('hostname', 'path_slug', 'port')},
        ),
    ]
